#!/bin/bash

USERNAME=$1
SERVER=$2
PORT=$3
PASSWORD=$4

COMMAND=$SSH_ORIGINAL_COMMAND


# Setup some environment

mkdir -p /tmp/ssh-irc/pid

PIDFILE=/tmp/ssh-irc/pid/$PPID
echo $1 >> $PIDFILE

mkdir -p ~/irssi-configs


function make_irssi 
{
cp $(dirname $0)/irssi-config-standard ~/irssi-configs/$USERNAME
cat <<EOF >> ~/irssi-configs/$USERNAME
settings = { core = {  user_name = "$USERNAME"; nick = "$USERNAME"; }; };
EOF
}

# Now handle the commands
case $COMMAND in 
    # just connect to irc
    "irc")
	echo if you are doing port forwarding you can connect your irc client now.
        ;;

    # boot irssi
    "irssi")
	[ ! -f ~/irssi-configs/$USERNAME ] && make_irssi $USERNAME
        irssi --config=~/irssi-configs/$USERNAME -c $SERVER -p $PORT -n $USERNAME -w $PASSWORD
	rm -f $PIDFILE
        ;;

    # send a chat chats
    "sendchat")
        echo "sendchat is not done yet. it's coming soon"
        ;;

    # download chats
    "backup")
        echo "backup is not done yet. it's coming soon"
        ;;

    # download logs
    "logs")
        echo "logs is not done yet. it's coming soon"
        ;;
 
    *)
        echo "unknown command"
        ;;

esac

# End

